import { test } from "node:test";
import assert from "node:assert/strict";
import * as sdk from "../sdk.js";

/**
 * Frozen v1.0 public SDK surface (runtime value exports).
 *
 * Removing or renaming any of these is a breaking change that requires a major
 * version bump. Adding a new export is additive (minor) and must be reflected
 * here deliberately. This snapshot makes accidental surface drift a failing test
 * rather than a silent break for downstream consumers.
 */
const FROZEN_SDK_SURFACE = [
  "ACTION_POLICY_REASON",
  "ACTION_REASON",
  "AUTHORITY_REASON",
  "AppendOnlyEvidenceLog",
  "BesaAdmissionError",
  "BesaMcpError",
  "BesaRuntimeError",
  "CAPABILITY_REASON",
  "DEFAULT_POLICY",
  "DELEGATION_REASON",
  "EVIDENCE_REASON",
  "FileReplayStore",
  "GRANT_REASON",
  "InMemoryReplayStore",
  "REASON",
  "REPLAY_REASON",
  "VerificationOnlyReplayStore",
  "addTrustAnchor",
  "admit",
  "admitAction",
  "admitAndConsume",
  "admitPreExecution",
  "applyKeyRotation",
  "canonicalize",
  "checkActionEnvelope",
  "checkGrant",
  "checkTrustedKey",
  "createActionCapability",
  "createActionEvidence",
  "createDelegation",
  "createEvidenceEnvelope",
  "createExternalAuthority",
  "createKeyRotation",
  "createKeyRotationWithProvider",
  "createReceipt",
  "createReceiptWithProvider",
  "emptyTrustStore",
  "findGrant",
  "findTool",
  "generateKeyPair",
  "getCount",
  "hashActionCapability",
  "hashActionConstraints",
  "hashActionEnvelope",
  "hashActionEvidence",
  "hashActionPolicy",
  "hashAuthorityAssertion",
  "hashDelegation",
  "hashExecutionResult",
  "hashExternalAuthority",
  "hashManifest",
  "hashPreExecutionReceipt",
  "hashPreExecutionRequest",
  "hashRequest",
  "increment",
  "isStoredKeyPair",
  "loadActionPolicy",
  "loadGrants",
  "loadManifest",
  "loadMeter",
  "meterKey",
  "normalizeAccessTokenAuthority",
  "normalizeDelegationAuthority",
  "normalizeWorkloadAuthority",
  "openKeyPair",
  "parseArtifactJson",
  "publicKeyId",
  "replayKey",
  "revokeTrustAnchor",
  "saveMeter",
  "sealKeyPair",
  "signManifest",
  "signManifestWithProvider",
  "signWithKeyPair",
  "signatureMessage",
  "validateActionCapability",
  "validateActionEnvelope",
  "validateActionEvidence",
  "validateActionPolicy",
  "validateDelegation",
  "validateExternalAuthority",
  "validateGrantSet",
  "validateKeyPair",
  "validateManifest",
  "validatePreExecutionReceipt",
  "validatePreExecutionRequest",
  "validateReceipt",
  "validateSignedManifest",
  "validateTrustStore",
  "verifyActionCapability",
  "verifyActionDelegation",
  "verifyActionEvidence",
  "verifyDelegationChain",
  "verifyExternalAuthority",
  "verifyKeyRotation",
  "verifyPreExecutionAdmission",
  "verifyReceipt",
  "verifyReceiptDetailed",
  "verifySignedManifest",
  "verifyTrustedSignedManifest",
  "withBesa",
  "withBesaExecutor",
  "withBesaMcp",
  "withPreExecutionAdmission",
];

test("public SDK export surface is frozen", () => {
  const actual = Object.keys(sdk).sort();
  assert.deepEqual(actual, FROZEN_SDK_SURFACE);
});
